#!/usr/bin/env node
// Weekly blog-draft generator.
//
// Reads every tool config and writes one markdown skeleton per tool into
// content/drafts/. It writes SKELETONS. It does not write articles, it does not
// touch WordPress, and it does not publish anything. A human writes the prose and
// clears every TODO before a draft goes anywhere near the live domain.
//
// Deliberately incapable of inventing facts: every sentence it emits comes from the
// tool config, which a human already wrote and reviewed. Everything that needs
// judgement is left as a TODO marker instead of being guessed at.
//
// Run: node scripts/blog-draft.mjs [--force]

import { mkdir, readdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { formatUpdated, resolveCta, toolUrl } from '../tools/lib/shell.ts';
// The calendar date where the person is, not where the server is. Already solved
// in calc/study-plan.ts and covered by its tests.
import { todayIso } from '../tools/calc/study-plan.ts';

const ROOT = path.resolve(import.meta.dirname, '..');
const CONFIG_DIR = path.join(ROOT, 'tools', 'config');
const DRAFT_DIR = path.join(ROOT, 'content', 'drafts');

/** Every config file is a tool. index.ts is the registry, not a tool. */
export async function loadTools(dir = CONFIG_DIR) {
  const files = (await readdir(dir))
    .filter((f) => f.endsWith('.ts') && f !== 'index.ts')
    .sort();

  const tools = [];
  for (const file of files) {
    const mod = await import(path.join(dir, file));
    tools.push(mod.default);
  }
  return tools;
}

const quote = (text) => text.split('\n').map((line) => `> ${line}`).join('\n');

/** Markdown skeleton for one tool. Pure — same input, same output. */
export function draft(tool, today = new Date()) {
  if (!tool || typeof tool.slug !== 'string' || tool.slug === '') {
    throw new TypeError('blog-draft: config has no slug, so there is nothing to draft.');
  }

  const url = toolUrl(tool.slug);
  const iso = todayIso(today);
  const generated = formatUpdated(iso);
  const cta = resolveCta(tool);

  const faq = tool.faq.map((item, i) => `
### ${i + 1}. ${item.q}

The tool page already answers this:

${quote(item.a)}

TODO(answer-${i + 1}): rewrite or cut. Do not paste it across. Two pages carrying the
same paragraph split the ranking between them and neither wins.
`).join('\n');

  const sources = tool.sources?.length
    ? tool.sources.map((s) => `- [${s.label}](${s.href})`).join('\n')
    : 'TODO(sources): every factual claim needs a primary source — the exam body, not\na competitor page. If a claim has no source, cut the claim.';

  return `---
title: "TODO(title)"
description: "TODO(description) — under 155 characters, written for a person, not a crawler."
tool: ${tool.slug}
tool_url: ${url}
read_minutes: ${tool.readMinutes}
status: draft
review: required
generated: ${iso}
---

<!--
  DRAFT SKELETON — generated by scripts/blog-draft.mjs from tools/config/${tool.slug}.ts.
  Nothing here is published. Clear every TODO before this is merged.

  House rules, restated because this is where they get broken:
  - Second person. "You can still write MAT", not "candidates may apply".
  - Short declarative opener, then a longer sentence that explains it. Vary the rhythm.
  - Lead with the honest answer even when it costs the sale.
  - No fear-selling. Never manufacture anxiety about someone's future to move a mock.
  - No statistic, cutoff, percentile or student result without a primary-source link.
    A missing number is cheap. An invented one is not.
  - An exam date is "expected" unless the exam body has published it.
-->

**Read time: ${tool.readMinutes} minutes** · Draft generated ${generated} · Not published

## Title

The tool page runs under:

${quote(tool.title)}

TODO(title): write a different one for the post, shaped \`[Situation]: [Solution]\`.
The post and the tool page cannot chase the same query — you would be competing with
yourself for one slot.

## Opening

TODO(open): two sentences. One short and declarative, then a longer one that explains
it. Someone landed here worried about one specific thing. Answer that first.

## What the tool does

${quote(tool.tagline)}

TODO(angle): the post is not a description of the tool. Pick the situation the reader
is actually in — the exam three weeks out, the score that came back lower than the
mocks, the form closing on Friday — and let the tool be the thing that resolves it.

## Outline

1. The situation, in the reader's words.
2. The honest answer, up front, before any setup.
3. How the calculation works, with one worked example.
   TODO(example): use a real Learn Crew scenario or the tool's own output. Never a
   competitor's worked example, and never a number you made up to make the maths tidy.
4. What the tool cannot tell you. TODO(limits): read the tool page and list the real ones.
5. What to do next.

## Questions to fold in

These come from the tool's FAQ, so they are questions people actually ask.
${faq}

## Try it

[${tool.title}](${url})

## Sources

${sources}

## Where this sends the reader

${cta.label} — ${cta.href}${cta.note ? `\n\n${cta.note}` : ''}

TODO(cta): one line in your own voice, placed after the reader has the answer.
Nothing is held back behind it.
`;
}

async function main() {
  const force = process.argv.includes('--force');
  await mkdir(DRAFT_DIR, { recursive: true });

  const tools = await loadTools();
  const written = [];
  const kept = [];

  for (const tool of tools) {
    const file = path.join(DRAFT_DIR, `${tool.slug}.md`);
    // An existing draft is someone's half-written article. Never overwrite it.
    if (existsSync(file) && !force) {
      kept.push(tool.slug);
      continue;
    }
    await writeFile(file, draft(tool), 'utf8');
    written.push(tool.slug);
  }

  console.log(`drafts written: ${written.length ? written.join(', ') : 'none'}`);
  if (kept.length) console.log(`left alone (already drafted): ${kept.join(', ')}`);
}

if (import.meta.filename === process.argv[1]) await main();
